---
# Copyright © 2020-2024 Matt Robinson
# Copyright © 2026 Nerijus Jasinskas
#
# SPDX-License-Identifier: MIT

name: Build
on:
#  push:
#    branches-ignore:
#      - dependabot/**
  workflow_dispatch:
#  schedule:
#    - cron: '30 12 * * 5'

permissions:
  contents: read

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    if: github.event_name != 'push' ||
        github.ref != 'refs/heads/update-version' ||
        github.event.head_commit.committer.name == 'github-actions[bot]'
    strategy:
      matrix:
        target:
          - aarch64-linux-android
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Build script
        run: |
          ./build
        env:
          TARGET: ${{ matrix.target }}
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Collect binaries and build info
        run: |
          mkdir output
          cp dropbear/dropbear output
          cp dropbear/dbclient output
          cp dropbear/dropbearkey output
          cp dropbear/dropbearconvert output
          cp dropbear/scp output
          cp dropbear/LICENSE output/LICENSE.txt

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target }}
          path: output

      - name: Upload build info as artifact
        if: matrix.target == 'aarch64-linux-android'
        uses: actions/upload-artifact@v7
        with:
          name: buildinfo
          path: buildinfo

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: compile

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Fetch artifacts
        uses: actions/download-artifact@v8

      - name: Extract version to environment vars
        run: |
          echo "BUILD_RELEASE=$(cat buildinfo/release)" >> "$GITHUB_ENV"

      - name: Latest release tag name
        id: latest_release
        uses: actions/github-script@v9
        with:
          result-encoding: string
          script: |
            const query = `query release($owner:String!, $repo:String!) {
              repository(owner:$owner, name:$repo) {
                releases(first:1, orderBy:{field:CREATED_AT, direction:DESC}) {
                  nodes {
                    tagName
                  }
                }
              }
            }`
            const vars = {
              owner: context.repo.owner,
              repo: context.repo.repo,
            }
            const result = await github.graphql(query, vars)
            const releases = result.repository.releases.nodes
            if (releases.length === 0) {
              return ''
            }
            console.log(`Previous latest release tag name=${releases[0].tagName}`)
            return releases[0].tagName

      - name: Package assets
        run: |
          zip --junk-paths dropbear-aarch64-linux-android.zip \
              aarch64-linux-android/*

      - name: Create release
        if: >
          env.BUILD_RELEASE != steps.latest_release.outputs.result &&
          github.ref == 'refs/heads/master'
        uses: actions/github-script@v9
        with:
          script: |
            const fs = require('fs')
            console.log("Creating release")

            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.BUILD_RELEASE,
              name: process.env.BUILD_RELEASE,
              body: "Dropbear SSH binaries for Android API level " +
                    fs.readFileSync("buildinfo/minsdk", "utf8").trimEnd() +
                    " and above, built with NDK version " +
                    fs.readFileSync("buildinfo/ndkver", "utf8").trimEnd(),
            })

            const assets = [
              'dropbear-aarch64-linux-android.zip',
            ]

            for(const asset of assets) {
              console.log("Uploading " + asset)
              await github.rest.repos.uploadReleaseAsset({
                headers: {
                  "content-type": "application/zip",
                },
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.data.id,
                data: fs.readFileSync(asset),
                name: asset,
              })
            }